# Imports

In [21]:
import numpy as np
from numpy import genfromtxt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from keras.models import Sequential
from keras.layers import Dense
from sklearn.metrics import confusion_matrix, classification_report

In [2]:
data = genfromtxt('Assets/bank_note_data.txt', delimiter=',')

In [3]:
data

array([[  3.6216 ,   8.6661 ,  -2.8073 ,  -0.44699,   0.     ],
       [  4.5459 ,   8.1674 ,  -2.4586 ,  -1.4621 ,   0.     ],
       [  3.866  ,  -2.6383 ,   1.9242 ,   0.10645,   0.     ],
       ...,
       [ -3.7503 , -13.4586 ,  17.5932 ,  -2.7771 ,   1.     ],
       [ -3.5637 ,  -8.3827 ,  12.393  ,  -1.2823 ,   1.     ],
       [ -2.5419 ,  -0.65804,   2.6842 ,   1.1952 ,   1.     ]])

In [4]:
labels = data[:, 4]

In [5]:
labels

array([0., 0., 0., ..., 1., 1., 1.])

In [6]:
features = data[:, 0:4]

In [7]:
features

array([[  3.6216 ,   8.6661 ,  -2.8073 ,  -0.44699],
       [  4.5459 ,   8.1674 ,  -2.4586 ,  -1.4621 ],
       [  3.866  ,  -2.6383 ,   1.9242 ,   0.10645],
       ...,
       [ -3.7503 , -13.4586 ,  17.5932 ,  -2.7771 ],
       [ -3.5637 ,  -8.3827 ,  12.393  ,  -1.2823 ],
       [ -2.5419 ,  -0.65804,   2.6842 ,   1.1952 ]])

In [8]:
X = features
y = labels

In [9]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [10]:
X_train

array([[-0.8734  , -0.033118, -0.20165 ,  0.55774 ],
       [ 2.0177  ,  1.7982  , -2.9581  ,  0.2099  ],
       [-0.36038 ,  4.1158  ,  3.1143  , -0.37199 ],
       ...,
       [-7.0364  ,  9.2931  ,  0.16594 , -4.5396  ],
       [-3.4605  ,  2.6901  ,  0.16165 , -1.0224  ],
       [-3.3582  , -7.2404  , 11.4419  , -0.57113 ]])

In [11]:
scaler_object = MinMaxScaler()

In [12]:
scaler_object.fit(X_train)

MinMaxScaler()

In [13]:
scaled_X_train = scaler_object.transform(X_train)

In [14]:
scaled_X_test = scaler_object.transform(X_test)

In [15]:
scaled_X_train

array([[4.44850688e-01, 5.14130449e-01, 2.18194638e-01, 8.50172258e-01],
       [6.53339968e-01, 5.82655745e-01, 9.93242398e-02, 8.17696322e-01],
       [4.81846700e-01, 6.69377018e-01, 3.61193167e-01, 7.63368407e-01],
       ...,
       [4.11050776e-04, 8.63104170e-01, 2.34046756e-01, 3.74261253e-01],
       [2.58284115e-01, 6.16029366e-01, 2.33861752e-01, 7.02643151e-01],
       [2.65661395e-01, 2.44444278e-01, 7.20316361e-01, 7.44775785e-01]])

In [17]:
model = Sequential()

model.add(Dense(4, input_dim = 4, activation='relu'))
model.add(Dense(8, activation='relu'))
model.add(Dense(1, activation='sigmoid'))

In [18]:
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [19]:
model.fit(scaled_X_train, y_train, epochs=50, verbose=2)

Epoch 1/50
29/29 - 1s - loss: 0.6864 - accuracy: 0.5560 - 563ms/epoch - 19ms/step
Epoch 2/50
29/29 - 0s - loss: 0.6777 - accuracy: 0.5669 - 21ms/epoch - 713us/step
Epoch 3/50
29/29 - 0s - loss: 0.6669 - accuracy: 0.6007 - 23ms/epoch - 779us/step
Epoch 4/50
29/29 - 0s - loss: 0.6545 - accuracy: 0.6888 - 25ms/epoch - 845us/step
Epoch 5/50
29/29 - 0s - loss: 0.6427 - accuracy: 0.7095 - 25ms/epoch - 845us/step
Epoch 6/50
29/29 - 0s - loss: 0.6299 - accuracy: 0.7584 - 24ms/epoch - 836us/step
Epoch 7/50
29/29 - 0s - loss: 0.6151 - accuracy: 0.7737 - 23ms/epoch - 784us/step
Epoch 8/50
29/29 - 0s - loss: 0.5979 - accuracy: 0.8150 - 25ms/epoch - 855us/step
Epoch 9/50
29/29 - 0s - loss: 0.5795 - accuracy: 0.8161 - 23ms/epoch - 791us/step
Epoch 10/50
29/29 - 0s - loss: 0.5591 - accuracy: 0.8183 - 21ms/epoch - 707us/step
Epoch 11/50
29/29 - 0s - loss: 0.5373 - accuracy: 0.8292 - 21ms/epoch - 715us/step
Epoch 12/50
29/29 - 0s - loss: 0.5151 - accuracy: 0.8379 - 22ms/epoch - 771us/step
Epoch 13/50
2

In [20]:
model.metrics_names

['loss', 'accuracy']

In [24]:
pred = (model.predict(scaled_X_test) > 0.5).astype("int32")

15/15 [==============================] - 0s 500us/step


In [25]:
confusion_matrix(y_test, pred)

array([[252,   5],
       [ 10, 186]], dtype=int64)

In [26]:
print(classification_report(y_test, pred))

              precision    recall  f1-score   support

         0.0       0.96      0.98      0.97       257
         1.0       0.97      0.95      0.96       196

    accuracy                           0.97       453
   macro avg       0.97      0.96      0.97       453
weighted avg       0.97      0.97      0.97       453



In [27]:
model.save('Assets/myModel.h5')

# To load model

In [28]:
from keras.models import load_model

In [29]:
newModel = load_model('Assets/myModel.h5')